### ISSUE TITLE
Pending Detection, Wrong Entries in recently viewed, Unable to Detect most of the time.

### ISSUE THREAD

**Issue by Asim707** [SIMKL/API#1]
Hey Developers,
Its a great concept and nicely developed app but there are number of issues i want to report. 
1) Firstly tracker is always in detecting video mode and it succesfully detected the video only one time.
2) Secondly there are always false entries in recently viewed list. I mean the shows that i have never even heard of appear in my recently viewed.
3) Then in most of the cases if by chance it moves from detecting video, it straight goes to unable to detect mode.
4) It detects video despite being in detection mode and mark it watched but that happens correctly very rarely. Say 3/10.
I use GOM player and its always up to date.
I have uninstalled the tracker, restarted my system, then installed it again, and restarted my system. Done this procedure multiple times but no use.
Kindly look into these issues.
Regards.

**Comment by masyk** [comment]
Please send this message to support@simkl.com with the name of the app you're using to track, it's not a question about the API, but the tracking software, thank you.
